FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80

#nginx = the web server
#alpine = a very small/lightweight Linux version
# destination is /usr .... docker container's nginx webpage folder
# expose 80 means web server uses port 80
